---
name: "Hoehn"
surname: ", Roman"
position: "B.Sc. Wirtschaftspaedagogik"
address: "Roedelstueck 26, 55129 Mainz"
phone: "Mobil: +49 178 4076394"
email: "rohoehn123@gmail.com"
github: "https://github.com/roman91DE/"
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```


# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Ausbildung

```{r}
library(tibble)

df_education = read.csv("../data/education.csv", header=TRUE, sep="|", quote = "\"")

df_education  %>% 
  detailed_entries(Abschluss, Jahr, Institution, Ort)
```

# Berufserfahrung

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

