---
title: Lebenslauf
name: Roman T. Hoehn
position: "B.Sc. Wirtschaftspädagogik"
address: "Rathenauplatz 6, 65203 Wiesbaden"
phone: "Mobil: +49 178 4076394"
email: "E-Mail: rohoehn123@gmail.com"
github: "Github: roman91DE"
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::markdowncv:
    #theme: kjhealy
    theme: davewhipp
    #theme: blmoore
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

## Über mich

 * **Masterstudent der Wirtschaftspädagogik mit Fokus auf Programmierung und maschinellem Lernen**
 * **Langjährige Erfahrung als Dozent für IT und BWL in der Erwachsenenbildung**
 
## Aus- und Weiterbildung

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Science - Wirtschaftspädagogik", "seit 2018", "Johannes Gutenberg-Universität", "Mainz, Deutschland",
  "Bachelor of Science - Wirtschaftspädagogik", "2014-2018", "Johannes Gutenberg-Universität", "Mainz, Deutschland",
  "Kaufmännische Ausbildung - Bürokaufmann", "2012-2014", "A. Panzer GmbH", "Wiesbaden, Deutschland",
  "Allgemeine Hochschulreife", "2007-2010", "Martin-Niemöller-Schule", "Wiesbaden, Deutschland"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

## Berufserfahrung

```{r}
library(tibble)
tribble(
  ~ Position, ~ Year, ~ Institution, ~ Where, ~Description,
  "Kaufmännischer Fachdozent", "seit 2018", "Kölner Wirtschaftsfachschule - Wifa-Gruppe - GmbH", "Mainz/Darmstadt, Deutschland", " Schwerpunkte: Office/IT, Volks- und Betriebswirtschaftslehre für kaufmännische Ausbildungsberufe",
  
"Wissenschaftliche Hilfskraft mit Abschluss", "2018-2019", "Johannes Gutenberg-Universität", "Mainz, Deutschland", "Programmierung und deskriptive Auswertung von Online Umfragen, Datenbankmanagement, Recherche- und Akquisearbeiten"
) %>% 
  detailed_entries(Position, Year, Institution, Where, Description)
```



## Fähigkeiten

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

