---
name: "Höhn,"
surname: "Roman"
# position: 
qualifications: "B.Sc. Wirtschaftspädagogik"
address: "Roedelstueck 26, 55129 Mainz"
phone: "Mobil: +49 178 4076394"
email: "rohoehn123@gmail.com"
profilepic: "../data/pic.jpeg"
headcolor: "414141"
github: roman91DE
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
  page_total: false
  show_footer: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```


# Über mich

```{r}
library(tibble)

df_aboutme = read.csv("../data/aboutme.csv", sep="?", quote = "\"")

df_aboutme  %>%
  detailed_entries(Stärken)
```

# Ausbildung

```{r}
library(tibble)

df_education = read.csv("../data/education.csv", sep="?", quote = "\"")

df_education  %>%
  detailed_entries(Abschluss, Jahr, Institution, Ort)
```

# Berufserfahrung

```{r}
library(tibble)

df_work = read.csv("../data/work.csv", sep="?", quote = "\"")

df_work  %>%
  detailed_entries(Tätigkeit, Jahr, Institution, Ort)
```

# Forschungsarbeiten

```{r}
library(tibble)

df_thesis = read.csv("../data/thesis.csv", sep="?", quote = "\"")

df_thesis  %>%
  detailed_entries(Fachbereich,Link,Thema,Art)
```


