---
name: "Roman Höhn"
position: "M.Sc. Wirtschaftspädagogik"
address: "Roedelstueck 26, 55129 Mainz"
phone: "+49 178 4076394"
email: "rohoehn123@gmail.com"
profilepic: "../data_de/pic2.jpg"
headcolor: "060606"
github: roman91DE
linkedin: roman-hoehn-893a48280
date: "`r format(Sys.time(), '%B %Y')`"
lang: "de"
output: 
  vitae::awesomecv:
    keep_tex: true
    page_total: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
Sys.setlocale("LC_TIME", "de_DE.UTF-8")
library(vitae)
library(tibble)

```


```{r echo=FALSE}
df_aboutme = read.csv("../data_de/aboutme.csv", sep="?", quote = "\"")
df_aboutme %>%
  detailed_entries(Beschreibung,a,Kategorie)

```

# Berufserfahrung

```{r}
df_work = read.csv("../data_de/work.csv", sep="?", quote = "\"")
df_work %>%
  detailed_entries(Tätigkeit, Jahr, Institution, Ort)

```

# Ausbildung

```{r}
df_education = read.csv("../data_de/education.csv", sep="?", quote = "\"")
df_education %>%
  detailed_entries(Abschluss, Jahr, Institution, Ort)

```


# Zertifikate

```{r}
df_cert = read.csv("../data_de/cert.csv", sep="?", quote = "\"")
df_cert %>%
  detailed_entries(Institution, Jahr, Titel, Ort)

```
\newpage

# Abschlussarbeiten

```{r}
df_thesis = read.csv("../data_de/thesis.csv", sep="?", quote = "\"")
df_thesis %>%
  detailed_entries(Fachbereich, Link, Thema, Art)

```

<!-- # Sonstiges -->

<!-- ```{r} -->
<!-- library(tibble) -->

<!-- df_misc = read.csv("../data_de/misc.csv", sep="?", quote = "\"") -->

<!-- df_misc  %>% -->
<!--   detailed_entries(Fähigkeit) -->
<!-- ``` -->



