---
name: "Roman Höhn"
position: "M.Sc. Business Education"
address: "Roedelstueck 26, 55129 Mainz"
phone: "Mobile: +49 178 4076394"
email: "rohoehn123@gmail.com"
profilepic: "../data_de/pic.jpeg"
headcolor: "060606"
github: roman91DE
date: "`r format(Sys.time(), '%B %Y')`"
lang: "eng"
output: 
  vitae::awesomecv:
  page_total: false
  show_footer: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```


# About Me

```{r}
library(tibble)

df_aboutme = read.csv("../data_eng/aboutme.csv", sep="?", quote = "\"")

df_aboutme  %>%
  detailed_entries(Strenghts)
```

# Education

```{r}
library(tibble)

df_education = read.csv("../data_eng/education.csv", sep="?", quote = "\"")

df_education  %>%
  detailed_entries(Degree, Year, Institution, Place)
```

# Professional Experience 

```{r}
library(tibble)

df_work = read.csv("../data_eng/work.csv", sep="?", quote = "\"")

df_work  %>%
  detailed_entries(Profession, Year, Institution, Place)
```

# Academic Projects

```{r}
library(tibble)

df_thesis = read.csv("../data_eng/thesis.csv", sep="?", quote = "\"")

df_thesis  %>%
  detailed_entries(Chair, URL, Topic, Project)
# Fachbereich,Link,Thema,Art
```


